# Generated by Django 4.2.9 on 2024-11-22 06:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootballField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(help_text='Primary contact number for inquiries.', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('contact_number2', models.CharField(blank=True, help_text='Secondary contact number (optional).', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('description', models.TextField(blank=True)),
                ('hourly_price', models.IntegerField(help_text='Hourly rental price for the field.', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('width', models.SmallIntegerField(help_text='Width of the field in meters.', validators=[django.core.validators.MinValueValidator(0)])),
                ('length', models.SmallIntegerField(help_text='Length of the field in meters.', validators=[django.core.validators.MinValueValidator(0)])),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='base.address')),
                ('images', models.ManyToManyField(blank=True, related_name='fields', to='file.file')),
            ],
        ),
    ]
