# Generated by Django 4.2.9 on 2024-11-22 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fields', '0001_initial'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='field',
            field=models.ForeignKey(help_text='The football field being booked.', on_delete=django.db.models.deletion.CASCADE, to='fields.footballfield'),
        ),
    ]
